language: rust
dist: xenial

services:
- docker

addons:
  apt:
    packages:
    - libssl-dev

script:
- apt-cache policy libssl-dev
- cargo test || travis_terminate 1;
- cargo build --release || travis_terminate 1;
- docker build -t spacestate_irc_bot . || travis_terminate 1;

before_deploy:
- docker save spacestate_irc_bot --output spacestate_irc_bot.tar

deploy:
  provider: releases
  api_key:
    secure: Nk2XqmXzR4DekWqEScvHBaxnaWLw8qpzjldBp268PFjLbpgWcjnalQmsW65yXokkz1OPsVf2f1pp4MI0mJ5LkfLTOGJEecA3olLe9SKMYgRnC0ejx7gpYE/Ig4Ohq+Y1P0HUKBDTpd0GX0x2avS99x40laptO8pdWI/VJGvSHk4bbdiagZfKJDWD/1UAs0JLj315962raknUBYqk6lU2r9d0G4eSc31dHwSRiMwRDc6hXswAUPx73N8Ou2CiFBvt/qOJqrkWotmCQ7D+S9/w9x4uInXec2gwBrn0JC+u/B1cGGM+1G6Qk30FT/kp0o6b/8P3dx4qN9K2o/iCxjQOqbqk/vVbV08OVWAYLl4tMMbkBLh6gZY3qSkW87hcgqpuPzRmn+VAopthCDe82jMYnLVIZzpd1hjg6iMZDtTdpqmjKweDcv7qJrRHO2xMToHs/BJZkgvYhHsjeWNy1JyZiluDwzPmnfrOd8LMpUewYNsm5xH3hyLTB3b3MzF6YxIY8IV5LpBaR/huhNYejA7FqBVYsUAP4gqe41Sa1G/36X8UaKpxTNOi22+6nw7GQ7L2sn8zpwUr9cPMn55v0hIfdMaq4bAPhaWEOyaSxYpfLikdDJO2NUhcBK+6ETScGvpLyNujnVRgSSl/pxVJDAVc5fuIiSh8zzaBaos/nOx1E4c=
  file: spacestate_irc_bot.tar
  skip_cleanup: true
  on:
    repo: pixelbar/spacestate_irc_bot
    tags: true
